### ISSUE TITLE
Create a loader shim for offline apps

### ISSUE THREAD

**Issue by modeswitch** [filerjs/filer#149]
Goals:
- Package an app as a compressed archive (`.tar.gz` or `.zip`)
- Loader script fetches package on first run and unpacks it into Filer
- Subsequent loads are done from Filer, so app can run fully offline
- Loader checks for package updates and downloads them, unpacking in Filer
- Loader reads config file to find app entry point (`index.html`?) and runs that
  - Easiest thing to do here is probably create an iframe inside the loader/launcher that contains the entry point
- Loader provides a live version of require.js that loads from Filer
- Loader accepts arguments to reinstall or delete app

This probably belongs in a separate repo.

**Comment by Pomax** [comment]
@humphd @modeswitch can this be closed? It's impossible to remove from github.com/issues/mentioned and the issue itself looks like it hasn't really impeded Filer use since then =)
