### ISSUE TITLE
test server runs on 127.0.0.1 on windows, rather than 0.0.0.0

### ISSUE THREAD

**Issue by Pomax** [filerjs/filer#281]
`grunt test-browser` reports running on 0.0.0.0:1234, but that IP is not available in Windows. The loopback 127.0.0.1 is, however, and navigating to http://127.0.0.1:1234 when running the browser tests work.

**Comment by humphd** [comment]
We use parcel now, and it reports `Server running at http://localhost:1234`.  Closing.
