### ISSUE TITLE
unable to set provider type in unit tests

### ISSUE THREAD

**Issue by modeswitch** [filerjs/filer#340]
?filer-provider=memory doesn't work anymore

**Comment by gideonthomas** [comment]
@sedge can I take this bug if you're not working on it and it still is an actual bug?

**Comment by humphd** [comment]
?It's probably not something I want to waste his cycles on at the moment.  I can take a look if you need it fixed, since I wrote that code and can probably track it down.

________________________________

**Comment by humphd** [comment]
?I totally misread that...you *want* to work on it :)  Yeah, go for it.  Ping me if you need guidance.

________________________________

**Comment by gideonthomas** [comment]
Awesome thanks! Planning to do this for one of my releases!

**Comment by gideonthomas** [comment]
@humphd we are able to set provider type only on perf-tests right? So `http://localhost:1234/perf/?filer-provider=WebSQL` should work, but currently it doesn't?
