### ISSUE TITLE
Use broadcast channels instead of intercom.js where possible

### ISSUE THREAD

**Issue by modeswitch** [filerjs/filer#349]
https://hacks.mozilla.org/2015/02/broadcastchannel-api-in-firefox-38/

**Comment by humphd** [comment]
Given that it's literally only supported in current Firefox, I'm not sure this is a great target (yet).

**Comment by modeswitch** [comment]
Yeah, that wasn't clear from the title.

**Comment by humphd** [comment]
This is happening in #571, closing.
