### ISSUE TITLE
Filer as a client for Ubuntu One File Sync server

### ISSUE THREAD

**Issue by humphd** [filerjs/filer#362]
This looks _really_ interesting, sort of like MakeDrive, but taken to the next level: https://insights.ubuntu.com/2015/08/10/ubuntu-one-file-syncing-code-open-sourced.

cc @Pomax

**Comment by Pomax** [comment]
hm, but there is the bit that states "**Do I have to sign a contributor agreement to modify the code?** No. This is no longer an active project, we are providing the code for public to read and use on their own."

**Comment by humphd** [comment]
I want to do more with syncing, but this looks dead.  Closing.
