### ISSUE TITLE
stats.isSymbolicLink() resturns false

### ISSUE THREAD

**Issue by livep2000** [filerjs/filer#368]
Great work, building an online OS ontop of it.
One part of it: an backup & restore utillity for Filer.

While traversing the directories and files to pack them, the type is stored as JSON.
Hitting a symbolic link with 'stat' the isSymbolicLink() function returns false.
And the type value holds 'FILE'.

**Comment by humphd** [comment]
Any chance I can get you to wrote a failing test case, or even just throw some pseudo code in here for what you're hitting?  Thanks.

https://github.com/filerjs/filer/blob/525e11f2033809731467ed1f04f8ba444c370b2b/tests/spec/fs.stats.spec.js#L154-L205

**Comment by modeswitch** [comment]
The behavior for `stat` on symbolic links is to return information about the file referred to by the link. To get information about symbolic link itself, you need to use `lstat` instead.

**Comment by modeswitch** [comment]
@livep2000 Please re-open if my comment didn't address your issue, and if there's an actual bug here I'm happy to investigate.

**Comment by livep2000** [comment]
No, you are absoluty correct. In the documentation it is mentioned also.
Thanks for the feedback.
