### ISSUE TITLE
Support for the Promise API.

### ISSUE THREAD

**Issue by dsych** [filerjs/filer#379]
There is a new [promise](https://nodejs.org/api/fs.html#fs_fs_promises_api) api that converts every callback method into promise-style api. Once converted, filer will be able to support async/await as well.

**Comment by humphd** [comment]
Yes, my plan is to use this as a way to get my new students to do their first PR this fall.  Lots of methods and tests and docs to write to support the new filehandle stuff.

**Comment by humphd** [comment]
i.e., please don't do this! :)

**Comment by dsych** [comment]
sorry @humphd, I've already hacked something together... would you care to take a look? it is really simple and converts all of the methods on the filehandler....

**Comment by dsych** [comment]
You can find it in #380

**Comment by humphd** [comment]
I think this is fine.  You still don't do all of the `FileHandle` stuff, nor do you have tests or docs, so I can have my students still do what I wanted even if we go with this.
