### ISSUE TITLE
Consider switching to Typescript

### ISSUE THREAD

**Issue by dsych** [filerjs/filer#381]
Although Typescript could be a little cumbersome to pick, it could be a great fit for the project. E.g. code is doing a lot of object creation based on prototytes, which before es6 classes is quite tricky; strong type cheking etc.
As shown [here](https://github.com/azu/parcel-typescript-example), parcel could be easely set-up to work with Typescript.

**Comment by modeswitch** [comment]
Double no on this.

I have a strong preference for using ES6/ES7 language features instead.
