### ISSUE TITLE
Promise based API does not work in v0.0.44 build

### ISSUE THREAD

**Issue by dnguneratne** [filerjs/filer#388]
## Issue
Issue #380 added a Promise based API but it is not included in release v0.0.44. I tried to run the following block of sample code from the readme file and it failed to execute.

```javascript
var Filer = require('filer.js');
var FileSystem = Filer.FileSystem;
var providers = FileSystem.providers;

const fs = new Filer.FileSystem({ provider: new providers.Memory() }).promises;
fs.open('/myfile', 'w+')
  .then(fd => fs.close(fd))
  .then(() => fs.stat('/myfile'))
  .then(stats => { console.log(`stats: ${JSON.stringify(stats)}`); })
  .catch(err => { console.error(err); })
``` 

## Expected behavior
![image](https://user-images.githubusercontent.com/8231763/45633491-e3bfce80-ba6d-11e8-84ba-13eaa7e856bf.png)

## Actual behavior
![image](https://user-images.githubusercontent.com/8231763/45633552-0eaa2280-ba6e-11e8-840f-907f93dffdf3.png)

## Environment
node v8.11.2

## Steps to reproduce
1. Create a file `myfile` in the same directory as `index.js`.
2. Run the above code snippet with `node index.js`.

## Attempts to fix - rebuild master
1. Clone filer.
2. `npm install`
3. `npm run build`
4. Change `var Filer = require('filer.js');`  
to `var Filer = require('C:\\path\\to\\filer\\dist\\filer.js');`
5. Run code snippet with `node index.js`

Code snippet successfully executes after this.

**Comment by humphd** [comment]
This just needs Filer to be re-built with `npm run build`.  Closing.
