### ISSUE TITLE
No test for truncate when length is undefined

### ISSUE THREAD

**Issue by humphd** [filerjs/filer#393]
I was [reading the docs for node.js](https://nodejs.org/api/fs.html#fs_fs_truncate_path_len_callback), and I notice that the following should work:

```js
fs.truncate(path, undefined, function(err) {
  // length of file should be 0 now
});
```

I would like to work on this, if that's OK.

**Comment by SeanPrashad** [comment]
Nobody else has taken it! Please let me know if you get stuck 😁
