### ISSUE TITLE
Add a test for fs.promises.stat() when the path does not exist

### ISSUE THREAD

**Issue by pynnl** [filerjs/filer#396]
The current [test](https://github.com/filerjs/filer/blob/fd3de6be2c1c19421d8c83e6791cd4b19afb84c7/tests/spec/fs.stat.spec.js#L13) needs to add a case for promise support. The new test can follow current one:
```javascript
it('should return an error if path does not exist', function(done) {
    var fs = util.fs();

    fs.stat('/tmp', function(error, result) {
      expect(error).to.exist;
      expect(error.code).to.equal('ENOENT');
      expect(result).not.to.exist;
      done();
    });
});
```
I'd like to work on this issue to add change to the current file if that's ok.

**Comment by humphd** [comment]
Go for it @pynnl.
