### ISSUE TITLE
Add tests for fs.promises.readdir

### ISSUE THREAD

**Issue by jespirit** [filerjs/filer#400]
I can rewrite the tests in [fs.readdir.spec.js](https://github.com/filerjs/filer/blob/master/tests/spec/fs.readdir.spec.js) to use Filer's Promises API

**Comment by humphd** [comment]
There are a few tests possible for this.  For example, if the path you specify is not found, if the path is actually a file, if the path exists and is a dir, etc.  Just pick one and do that, and let others add the remaining cases.

**Comment by jespirit** [comment]
I'll test `fs.promises.readdir` by passing in a file.
