### ISSUE TITLE
Add a test for fsPromises chmod

### ISSUE THREAD

**Issue by danielbogomazov** [filerjs/filer#405]
There is currently no test for the promises version of chmod in filer/tests/spec/fs.chmod.spec.js
I can add a test case for this. 

I can also look at fchmod but I'm unsure if there's a promises version. chmod is documented here https://nodejs.org/api/fs.html#fs_fspromises_chmod_path_mode but there is no fchmod promises documentation. I can test it out when writing the chmod test case and if fchmod also works with promises I could include it in my PR.

**Comment by humphd** [comment]
You can do either or both, as you like.  Go for it @danielbogomazov!
