### ISSUE TITLE
Add test for fs.promises.rename() to test for renaming an existing directory

### ISSUE THREAD

**Issue by bblarney** [filerjs/filer#417]
I noticed that [a test has been added](https://github.com/filerjs/filer/pull/416) for promises.rename() to test for renaming an existing file.

I would like to create a test for renaming an existing directory using promises, and add it to the [test file](https://github.com/filerjs/filer/blob/master/tests/spec/fs.rename.spec.js)

**Comment by humphd** [comment]
Go for it @bblarney.
