### ISSUE TITLE
Add tests for fsPromises.rmdir

### ISSUE THREAD

**Issue by Casva** [filerjs/filer#427]
There are currently no tests for [fsPromises.rmdir(path)](https://nodejs.org/docs/latest/api/fs.html#fs_fspromises_rmdir_path)

I would like to create the tests for [when the provided path doesn't exist](https://github.com/filerjs/filer/blob/master/tests/spec/fs.rmdir.spec.js#L13) and for [when the user tries to remove the root directory](https://github.com/filerjs/filer/blob/master/tests/spec/fs.rmdir.spec.js#L23)

Could I get this issued assigned to me?
Thanks!

**Comment by humphd** [comment]
Go for it @Casva, it's all yours.
