### ISSUE TITLE
Add test for fsPromises.unlink() when trying to remove a directory.

### ISSUE THREAD

**Issue by jagmeetb** [filerjs/filer#431]
Currently the [unlink() tests](https://github.com/filerjs/filer/blob/master/tests/spec/fs.unlink.spec.js) do not contain a test for [fsPromises.unlink()](https://nodejs.org/docs/latest/api/fs.html#fs_fspromises_unlink_path). The code for a test like this would be very similar to the ones already existing for fs.unlink()

```js
it('should not unlink directories', function (done) {
  var fs = util.fs();

  fs.mkdir('/mydir', function (error) {
    if(error) throw error;

    fs.unlink('/mydir', function (error) {
      expect(error).to.exist;
      expect(error.code).to.equal('EPERM');

      fs.stat('/mydir', function (error, stats) {
        expect(error).not.to.exist;
        expect(stats).to.exist;
        expect(stats.type).to.equal('DIRECTORY');
        done();
      });
    });
  });
});
```

I would like to be assigned this issue if possible.

**Comment by humphd** [comment]
Great, go for it @jagmeetb.
