### ISSUE TITLE
Add mkdtemp method

### ISSUE THREAD

**Issue by AlexeiGitH** [filerjs/filer#441]
Node.js File System module has a method [mkdtemp](https://nodejs.org/api/fs.html#fs_fs_mkdtemp_prefix_options_callback), used to create a temporary directory. 

I would like to implement this method in Filer, before adding tests methods, mentioned in issue #394 

`
  fs.mkdtemp(prefix, callback);
`

Here prefix is a name for a temporary directory. 6 random characters will be appended to the name to make sure directory is unique.
Error and path to created directory will be passed to a callback.

All temp directories will be created in /tmp.

**Comment by humphd** [comment]
Sounds good.  One thing to note: I don't think `node` assumes you'll always put your temp files in `/tmp`.  My reading of the docs is that you specify a prefix, and it uses that.  So for example you could do: `mkdtemp('/tmp/', callback)` and it will create `/tmp/ay3ri1`.  But you could also use `mkdtemp('/foo/tmp-', callback)` and get `/foo/tmp-ay3ri1`.  We should confirm this so we match what node does.

**Comment by AlexeiGitH** [comment]
I assumed that all new tmp directories will be created in /tmp.

I will test how node handles cases you mentioned, and will update mkdtemp method accordingly.

**Comment by humphd** [comment]
Finished in https://github.com/filerjs/filer/commit/0eb7066a861d9d4506a4b2b2bb10865379aab82c
