### ISSUE TITLE
Add tests for fsPromises.link

### ISSUE THREAD

**Issue by Dragomegak** [filerjs/filer#453]
I found that there are no tests for fs.promises version of mkdir method.
The new tests can be identical to [fs.link version](https://github.com/filerjs/filer/blob/master/tests/spec/fs.link.spec.js):
- should be a function
- should create a link to an existing file
- should create hard link to identical data node
- should not follow symbolic links
- should not allow links to a directory

I would not be implementing the tests for checking return type as [issue #421](https://github.com/filerjs/filer/issues/421) exists

I would like to take this issue and work on it if possible. (although I just finished it)

**Comment by humphd** [comment]
Great, it's all yours @Dragomegak
