### ISSUE TITLE
Add test for fs.copyFile

### ISSUE THREAD

**Issue by YuechengWu** [filerjs/filer#459]
There is currently no test for fs.copyFile().

I would like to create a test if the root directory does not exist or the file does not exist and it should throw an error.
ex. fs.copyFile('\undefinedRootDirectoryFile', 'destination.txt', (err) => { ... }

Please if I could be assigned to work on this issue.

Thank you!

Yuecheng Wu

**Comment by humphd** [comment]
See also #436 which, which another student filed.  You could collaborate on this feature a bit.
