### ISSUE TITLE
Add a test for fs.read when attempting to read a file that does not exist

### ISSUE THREAD

**Issue by CometS1** [filerjs/filer#461]
I noticed that for the current [fs.read](https://github.com/filerjs/filer/blob/master/tests/spec/fs.read.spec.js) tests there is no test to see if an error is received when attempting to read a file that does not exist. 

I would like to create a test to make sure an error is received when attempting to read a file that does not exist.

**Comment by humphd** [comment]
Sounds good @CometS1, nice catch.  Go for it.
