### ISSUE TITLE
add tests for fsPromises.chown()

### ISSUE THREAD

**Issue by ThomasNolte** [filerjs/filer#465]
currently there are no tests involving the promises version of the fs.chown() function. 

fs.chown() currently has tests for
- should be a function
- should automatically set file uid/gud to 0
- should allow updating of uid/gid

I would like to be assigned to implement these same tests for fs.promises.chown().

Thanks,

Thomas N

**Comment by humphd** [comment]
Great, go for it @ThomasNolte.
