### ISSUE TITLE
Add test for fs.chmod

### ISSUE THREAD

**Issue by rhayes2** [filerjs/filer#467]
This test i don't think is written,

**Comment by humphd** [comment]
@rhayes2 yeah, we need these.  The `fs.chmod` code is in, but there are zero tests.  Would be good to add it.

**Comment by rhayes2** [comment]
having alot of issues setting things up on my non-main pc cause i had to go away, getting many git errors :O ugh

**Comment by humphd** [comment]
If you want to hop on Slack and discuss, we can do that.  Or put some info in here?

**Comment by humphd** [comment]
Here's one suggestion for how to test `fs.chmod`.

1. In this file https://github.com/filerjs/filer/blob/master/tests/spec/fs.chmod.spec.js
2. You want to add a new `it()` test block like the others
3. Add a test for the case that you pass an invalid `mode`, something like `1000`, and it should `expect` the `callback` to get an error or type `EINVAL`
