### ISSUE TITLE
Add test cases for fsPromises.rmdir

### ISSUE THREAD

**Issue by thanhcng** [filerjs/filer#474]
I would like to work on tests for `fsPromises.rmdir` on these two cases:
* [Should return an error if the directory is not empty](https://github.com/filerjs/filer/blob/fd3de6be2c1c19421d8c83e6791cd4b19afb84c7/tests/spec/fs.rmdir.spec.js#L33)
* [Should return an error if the path is not a directory](https://github.com/filerjs/filer/blob/fd3de6be2c1c19421d8c83e6791cd4b19afb84c7/tests/spec/fs.rmdir.spec.js#L49)

It would be great if you can assign this issue to me.
Thank you very much!

I added a pull request #510

**Comment by humphd** [comment]
OK, go for it @thanhcng
