### ISSUE TITLE
Adding test for fs.exists() when it follows symbolic link and can't find directory

### ISSUE THREAD

**Issue by iblacker** [filerjs/filer#475]
I have noticed the test **fs.exists()** doesn't account for the case when the the path is a symbolic link and there is no resulting directory.

I would like to add the test for that. What do you think?

Alternatively I could also create a test for **fs.rmdir()** to test when the target is a (hard) link, which the test should fail.

@humphd

**Comment by humphd** [comment]
OK, go for it @iblacker
