### ISSUE TITLE
Failing eslint does not always fail the build

### ISSUE THREAD

**Issue by 0xazure** [filerjs/filer#482]
In reviewing #478, I ran into a failure in eslint when running the PR locally. The CI build for the PR succeeded, however viewing [the build details](https://travis-ci.org/filerjs/filer/builds/432510814) shows the same lint error but exited `0`.

I'm also not sure why the build exited `0` when locally `npm test` on the same PR exits `1`.

@humphd is this intended?

**Comment by humphd** [comment]
I reran that build, and it failed as expected.  I guess this is an intermittent bug in Travis?  Very odd

https://travis-ci.org/filerjs/filer/builds/432510814

**Comment by 0xazure** [comment]
Definitely seems like an intermittent Travis issue. Closing for now since the issue wasn't repeatable on the same branch and is likely an infrastructure problem.
