### ISSUE TITLE
Adding documentation for avoiding "Expected linebreaks to be 'LF' but found 'CRLF'  linebreak-style" error

### ISSUE THREAD

**Issue by Mordax** [filerjs/filer#490]
So I have seen a few classmates struggle with running Filer tests when their git config --global core.autocrlf is set to true. 

It would be nice to have documentation that mentions that they should set that config for the filer repo to false or changing the .eslintrc.json linebreak style to Windows. 

What do you think @humphd ?

**Comment by humphd** [comment]
See also #403.  Yes, we should ponder this.  I'm going to close this as a dupe, but I agree that it needs some thought.
