### ISSUE TITLE
Converting an existing mkdir callback test to use promises

### ISSUE THREAD

**Issue by yevseytsev** [filerjs/filer#491]

**Comment by humphd** [comment]
OK @yevseytsev, go for it.  One tip when you're filling issues: use a shorter title, and then put the bulk of your info in the comment for the Issue.  In your case, you could have done:

Title: Add test for mkdir with restricted symbols.
Body: I noticed that there isn't a test for the case that you call `mkdir` with a path that includes a restricted symbol.  It should fail to create the illegal path name.

**Comment by yevseytsev** [comment]
I have talked to you on Slack, and we decided that I will convert an existing mkdir callback test to use promises vs. current issue, since this isn't a real bug
