### ISSUE TITLE
Integrate Prettier to enforce a style guide

### ISSUE THREAD

**Issue by SeanPrashad** [filerjs/filer#537]
[This](https://github.com/filerjs/filer/pull/509#issuecomment-425444675) comment in #509 made me realize that there is a lot of unnecessary energy spent reviewing others code just to mention white space, or other formatting issues.

We should investigate [Prettier](https://prettier.io/), a tool that enforces our [.eslintrc.json](https://github.com/filerjs/filer/blob/master/.eslintrc.json) configuration and automatically corrects stylistic errors.

**Comment by SeanPrashad** [comment]
Just curious - was it implemented as a command or git pre-commit hook? I've used it with [pretty-quick](https://prettier.io/docs/en/precommit.html#option-2-pretty-quick-https-githubcom-azz-pretty-quick) before and it didn't deviate from the regular git workflow.

**Comment by humphd** [comment]
Both.  Also, we found bugs in the tooling *around* prettier which caused us to back it out.  Again, not saying it can't be done properly, but I haven't been on a project where it was.

**Comment by SeanPrashad** [comment]
I'd love to hear about the findings - if you have time, let's discuss it offline
