### ISSUE TITLE
Deal with changes to node's Buffer

### ISSUE THREAD

**Issue by humphd** [filerjs/filer#547]
In node, `new Buffer(8)` gives `[DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.`  We should prepare for this, and alter how we expect to use Buffers in Filer.

**Comment by ilDon** [comment]
Great to see this being addressed. I am currently using Filer.Buffer in a isomorphic app and on Node I'm getting this issue.

**Comment by humphd** [comment]
@ilDon, would you be willing to toss a snippet of code similar to what you're doing in your APP, and then I can add a regression test for the case you need to make sure we support.  Thanks.

**Comment by ilDon** [comment]
I'm using `Filer.Buffer` to generate the Buffer like so (TypeScript):

    import * as Filer from 'filer';

    export class FileBuffer {

      public static generateFileBuffer(fileArrayBuffer: ArrayBuffer | Uint8Array | Array<number>): Buffer {
        return Filer.Buffer(fileArrayBuffer);
      }

    }

**Comment by humphd** [comment]
OK, this is done.  We'll do what node does and support both ways (ctor + `.alloc()`/`.from()`).
