### ISSUE TITLE
Mkdir() - Add functionality for recursive property

### ISSUE THREAD

**Issue by SeanPrashad** [filerjs/filer#550]
With the introduction of recursive functionality[ landing recently](https://github.com/nodejs/node/pull/21875) for `mkdir` in [Node 10.12.0](https://nodejs.org/api/fs.html), we should mirror that for Filer.

The `-p` argument specifies creating the entire folder structure, which is a huge improvement for developers since it's [been around forever](http://man7.org/linux/man-pages/man1/mkdir.1p.html#OPTIONS).

**Note**: This is not a new function but simply an optional boolean flag with the default being `false`. We'll need to update it in a [handful of places](https://github.com/filerjs/filer/search?q=mkdir&unscoped_q=mkdir), starting with the following areas:

* [`fs.mkdir.spec.js`](https://github.com/filerjs/filer/blob/27659d45da05ccb3b40cf331ca3db769cc27d9e1/tests/spec/fs.mkdir.spec.js)
* [`README`](https://github.com/filerjs/filer#mkdir)

**Comment by humphd** [comment]
Dupe of #414

**Comment by SeanPrashad** [comment]
See #479 for a WIP PR
