### ISSUE TITLE
Implement fs.access() method

### ISSUE THREAD

**Issue by humphd** [filerjs/filer#558]
@deepanjali19 noticed that we don't have any implementation for `fs.access()`:

* [node docs for `fs.access`](https://nodejs.org/api/fs.html#fs_fs_access_path_mode_callback)
* [code in node.js](https://github.com/nodejs/node/blob/af6d26281f734dbbf1bf497103d1cb4b85a52b2e/lib/fs.js#L174)

The general pattern for implementing a new method like this in Filer is to do the following:

1. Add the new `access` method name to the [interface list](https://github.com/filerjs/filer/blob/master/src/filesystem/interface.js#L271-L305)
1. Next add a new exported method name for `access` to [this list in the implementation file](https://github.com/filerjs/filer/blob/master/src/filesystem/implementation.js#L2386L2420).
1. Now add a new file to the tests: `tests/spec/fs.access.js`.  Add a very simple set of tests to start (you can add more later below), something like this:

    ```js
    var util = require('../lib/test-utils.js');
    var expect = require('chai').expect;

    describe('fs.chmod, fs.fchmod', function() {
       beforeEach(util.setup);
       afterEach(util.cleanup);

       it('should be functions', function() {
           var fs = util.fs();
           expect(typeof fs.access).to.equal('function');
       });
    });
    ````
1. Add your new test file `tests/spec/fs.access.js` to the list of [`required()` test files here](https://github.com/filerjs/filer/blob/master/tests/index.js#L10-L44).
1. Write an implementation for the `fs.access` method in `implementation.js` that looks something like this:
    ```js
    function access(fs, context, path, mode, callback) {
        //...
    }
    ```
    You need to do a few things here.  You'll have to deal with the `mode` not being given, and instead getting `callback` on `mode`.  You can look at various other functions in this file which deal with the same problem, for example [`mkdir`](https://github.com/filerjs/filer/blob/master/src/filesystem/implementation.js#L1675-L1686)
1. Next you'll need to write a function `access_file` which gets called by your `access` function.  Basically, the `access` function is the public API, and here you need to deal with all the various arguments being passed in (e.g., set defaults, check that things make sense).  Then, the bulk of the work happens in `access_file`.  In our case, we'll need to get the filesystem `Node` for the given path, get it's `mode`, and then do bitwise comparison to see if the `mode` flag passed to `access` matches.  I can help you more when you get to this stage.
1. Finally, we'll need to write all the tests for every possible case of calling `fs.access` with different paths, modes, etc.

Assigning to @deepanjali19, who offered to work on this.  Please let me know if you have questions, and I can help guide you.

**Comment by deepanjali19** [comment]
Thank you so much @humphd ! I was heading the right direction with find_node and you guided me further at the right time. I will work on it now and will let you know if I have any question. :)
