### ISSUE TITLE
Remove duplicate stat.h constants defined in constants.js

### ISSUE THREAD

**Issue by humphd** [filerjs/filer#585]
We are defining these twice (we can just use the ones node has on fs.constants);

```
  S_IFREG: 0x8000,
  S_IFDIR: 0x4000,
  S_IFLNK: 0xA000,
```

from https://github.com/filerjs/filer/blob/master/src/constants.js#L27-L29

and instead we can use them from https://github.com/filerjs/filer/blob/master/src/constants.js#L96

**Comment by yuzhouChen** [comment]
I will work on this
