### ISSUE TITLE
Add test for fs.readlink() when the path isn't a symbolic link

### ISSUE THREAD

**Issue by humphd** [filerjs/filer#625]
https://codecov.io/gh/filerjs/filer/src/master/src/filesystem/implementation.js#L1236 is a branch we don't test.  To hit it, I think we need:

* add a test to `fs.readlink.spec.js`
* create a file
* call `fs.readlink` on the file
* expect an `EINVAL` error to be returned

The test needs to be nearly identical to [this test](thttps://github.com/filerjs/filer/blob/master/tests/spec/fs.link.spec.js#L99), but we need a file vs. the root directory, which is empty.

```js
it('should return an error if the path is not a symbolic link', function(done) {
    var fs = util.fs();

    fs.readlink('/', function(error) {
      expect(error).to.exist;
      expect(error.code).to.equal('ENOENT');
      done();
    });
});
```

**Comment by humphd** [comment]
Add another test identical to the one above, but instead of calling `readlink` with a file, pass it a directory you create (not the root directoy).

**Comment by rscotchmer** [comment]
Hi @humphd, I'd like to tackle this issue!

**Comment by humphd** [comment]
Sounds good @rscotchmer, let me know if you need any advice.
