### ISSUE TITLE
Add tests for fs.write to increase coverage

### ISSUE THREAD

**Issue by humphd** [filerjs/filer#627]
We have a bunch of missed branches in our `fs.write` code: https://codecov.io/gh/filerjs/filer/src/master/src/filesystem/implementation.js#L1833.  To improve it, we need:

* test that tries to use a non-existent `fd`
* test that tries to open a file without the `O_WRITE` flag and then call `fs.write`
* test that tries to write a `buffer` whose length is too small (`buffer.length - offset < length`)

**Comment by rscotchmer** [comment]
Hello!  I'd like to fix this issue if that's alright!

**Comment by humphd** [comment]
Sounds good @rscotchmer, go for it.
