### ISSUE TITLE
update tests/spec/fs.readlink.spec.js to use const, let and strict mode       

### ISSUE THREAD

**Issue by yuansheng1989** [filerjs/filer#660]
fs.readlink.spec.js is using var. It should be replaced by let or const in strict mode.

**Comment by humphd** [comment]
Sounds good @yuansheng1989, it's all yours.

**Comment by humphd** [comment]
NOTE: when you do a PR, you can tell GitHub to automatically close the associated issue by using "Fixes #660" in your PR description.
