### ISSUE TITLE
Update "filer/blob/master/tests/spec/fs.watch.spec.js" for ES6 variable declaration style

### ISSUE THREAD

**Issue by vrozin** [filerjs/filer#666]
Hello,
May I be assigned to update the file mentioned above to change the declaration of the variables from "var" to "let" and "const"?

**Comment by humphd** [comment]
Go ahead @vrozin, it's all yours.

**Comment by humphd** [comment]
When you do a PR that fixes a bug, you can leave a comment in the PR that says "Fixes #666" and GitHub will automatically close the issue when the PR gets merged.
