### ISSUE TITLE
Update code in filer/src/stats.js to use const instead of var in loading modules

### ISSUE THREAD

**Issue by AlvinValdez** [filerjs/filer#670]
var Constants = require('./constants.js');
var Path = require('./path.js');

Should replace the var with const

**Comment by humphd** [comment]
@AlvinValdez sure, you can work on this.  NOTE: when you file an issue, you need a description to go with it, vs. just a title.  Can you edit this issue (three dots on the top-right of your original comment, and then Edit) to add one?
