### ISSUE TITLE
Update "filer/tests/spec/fs.unlink.spec.js" to use "let" or "const" instead of "var"

### ISSUE THREAD

**Issue by PriyankaCodes99** [filerjs/filer#685]
The current version of "filer/tests/spec/fs.unlink.spec.js" file uses "var". Replacing the "var" declarations with "const" or "let" is needed in order to be compliant with ES6.

**Comment by humphd** [comment]
Go for it @PriyankaCodes99.

**Comment by PriyankaCodes99** [comment]
This issue is in progress currently.

**Comment by PriyankaCodes99** [comment]
Please see pull request #733.
