### ISSUE TITLE
Update ' filer/src/shell/environment.js' file to use const/let instead of var

### ISSUE THREAD

**Issue by pbrahmbhatt3** [filerjs/filer#698]
The file  'filer/src/shell/environment.js' has variables that are constants and are declared using var. It has to be updated by using const instead.

**Comment by pbrahmbhatt3** [comment]
Hi @humphd, just wanted to make sure if I can go for it in case no one is working on it?

**Comment by humphd** [comment]
@pbrahmbhatt3 this is a huge file, you sure you want to do it?  You'll need to do it throughout the entire file.  If that's OK, go for it.  But also, feel free to grab a smaller file if you want.

**Comment by pbrahmbhatt3** [comment]
I have taken a new file now. Is it okay? @humphd

**Comment by humphd** [comment]
You can tell GitHub to automatically close an issue when a PR is merged by adding "Fixes #698" in the PR's description.
