### ISSUE TITLE
Shell.mkdirp does not support relative paths

### ISSUE THREAD

**Issue by SillyFreak** [filerjs/filer#755]
exactly as the title says. trying it gives me `(EINVAL): Path must be absolute.`

As a workaround, replacing `path` by `Path.resolve(sh.pwd(), path)` works of course.

**Comment by humphd** [comment]
Looks like we're missing a call to `Path.resolve(sh.pwd(), path)` in [`mkdirp`](https://github.com/filerjs/filer/blob/master/src/shell/shell.js#L381-L440).

**Comment by SillyFreak** [comment]
hey @humphd, I'm back :P

If you don't mind, I'll try and create a PR for this; I have never before contributed to someone else's project beyond reporting bugs and would like to get into the habit. I've read the CONTRIBUTING.md and will try to create a fitting test case for the fix.

**Comment by humphd** [comment]
@SillyFreak sounds good.  If you need help getting things to work, let me know.

**Comment by humphd** [comment]
v1.2.0 Released!

- https://www.npmjs.com/package/filer/v/1.2.0
- https://github.com/filerjs/filer/releases/tag/v1.2.0

Thanks for contributing.
