### ISSUE TITLE
Incorrect documentation for Buffer shim

### ISSUE THREAD

**Issue by bcheidemann** [filerjs/filer#769]
Using the example webpack config results in the Buffer being resolved incorrectly. Webpack resolves Buffer globally to:
`{ __esModule: true, default: ... , Buffer: ... }`

Fixed by #768

**Comment by humphd** [comment]
If you use `Fixes #768` in your PR description, it will auto-close these.

**Comment by bcheidemann** [comment]
Thanks, will do this in future 👍
